### ISSUE TITLE
Need a name - any ideas welcome

### ISSUE THREAD

**Issue by sjaehn** [sjaehn/BOops#1]
The project started as "B.Glitchr". Some other suggestions:
* B.Mess
* B.Wildr
* B.Pandora
* B.GlitchBoxx
* B.GlitJar

What do you prefer? Any other ideas?

**Comment by alex-tee** [comment]
B.Glitch08 or B.Glitchr

I think B.Glitchr fits best with the rest of the plugins and sounds kewl

**Comment by sub26nico** [comment]
B.Happy :-)

**Comment by sjaehn** [comment]
Thanks for your ideas. Now it has got a name.
