### ISSUE TITLE
Strange error in lv2vst 

### ISSUE THREAD

**Issue by KottV** [sjaehn/BOops#11]
Hi,

When BOops loaded via https://github.com/x42/lv2vst then selecting **Oops** effect throws an error:
```
Creating VST instance: lv2vst
Initialising VST: lv2vst (1.0.0.0)
Opening VST UI: B.Oops
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Can't open /usr/lib64/lv2/BOops.lv2inc/oops44100.wav.
```

it can be fixed by simple changing https://github.com/sjaehn/BOops/blob/master/src/FxOops.hpp#L50
to
```
strcat (samplepath, "/inc/oops44100.wav");
```

but there is no such error in other native LV2 hosts, such jalv.gtk or Carla.

**Comment by sjaehn** [comment]
Thanks for info. I haven't tested it with lv2vst yet. It looks like lv2vst instantiates the plugin with its bundle_path but without closing slash.

Also interesting: What about the UI (after your fix)? The background image effect controls background and all slot labels are implemented in the same way: pluginPath + "inc/" + filename. Thus, you shouldn't see any slot/effect labels. What do you see?

And of course the line below your fix is a bug. I should catch that exception.

**Comment by sjaehn** [comment]
I fixed it by checking for the closing slash at plugin instantiation in 382baa655ee6fb6ebefccb4738cefd9359e4939d . Also fixed the lacking exception handling. I hope it will work now.

I'll also take this fix (in the UI) along to all other B.* plugins.

**Comment by KottV** [comment]
Images loads fine with my "fix", seems like the only sample path was affected
![изображение](https://user-images.githubusercontent.com/4686351/107582754-b3cc8380-6c45-11eb-97fe-71bf1f2bc68c.png)

**Comment by KottV** [comment]
> I fixed it by checking for the closing slash at plugin instantiation in [382baa6](https://github.com/sjaehn/BOops/commit/382baa655ee6fb6ebefccb4738cefd9359e4939d) . Also fixed the lacking exception handling. I hope it will work now.

Great! It works. Thank you.
