### ISSUE TITLE
Having difficulty building

### ISSUE THREAD

**Issue by eufex** [sjaehn/BOops#14]
Hi
Trying to build 1.2.6 on Ubuntu 20.04.
Dependencies are installed but when attempting to MAKE I get
Build BOops.lv2 DSP...src/BOops.cpp: In member function ‘LV2_State_Status BOops::state_save(LV2_State_Store_Function, LV2_State_Handle, uint32_t, const LV2_Feature* const*)’:
src/BOops.cpp:1176:3: error: ‘LV2_State_Free_Path’ was not declared in this scope; did you mean ‘LV2_State_Make_Path’?
 1176 |   LV2_State_Free_Path* freePath = NULL;
      |   ^~~~~~~~~~~~~~~~~~~
      |   LV2_State_Make_Path
src/BOops.cpp:1176:24: error: ‘freePath’ was not declared in this scope
 1176 |   LV2_State_Free_Path* freePath = NULL;
      |                        ^~~~~~~~
src/BOops.cpp:1181:4: error: ‘LV2_STATE__freePath’ was not declared in this scope; did you mean ‘LV2_STATE__makePath’?
 1181 |    LV2_STATE__freePath, &freePath, false,
      |    ^~~~~~~~~~~~~~~~~~~
      |    LV2_STATE__makePath
src/BOops.cpp: In member function ‘LV2_State_Status BOops::state_restore(LV2_State_Retrieve_Function, LV2_State_Handle, uint32_t, const LV2_Feature* const*)’:
src/BOops.cpp:1306:2: error: ‘LV2_State_Free_Path’ was not declared in this scope; did you mean ‘LV2_State_Make_Path’?
 1306 |  LV2_State_Free_Path* freePath = nullptr;
      |  ^~~~~~~~~~~~~~~~~~~
      |  LV2_State_Make_Path
src/BOops.cpp:1306:23: error: ‘freePath’ was not declared in this scope
 1306 |  LV2_State_Free_Path* freePath = nullptr;
      |                       ^~~~~~~~
src/BOops.cpp:1311:3: error: ‘LV2_STATE__freePath’ was not declared in this scope; did you mean ‘LV2_STATE__makePath’?
 1311 |   LV2_STATE__freePath, &freePath, false,
      |   ^~~~~~~~~~~~~~~~~~~
      |   LV2_STATE__makePath
make: *** [makefile:128: BOops.so] Error 1

cheers

**Comment by sjaehn** [comment]
`freePath` is a rather new feature that was requested for B.Oops by Reaper (see #9 ) but wasn't supported on the release day of Ubuntu 20.04 (focal). Thus, the version 1.2.6 (and only this version) needs lv2 >= 1.18.0. I recommend to download or clone the current master (called 1.2.7). The current master is compatible to older versions and only needs lv2 >= 1.14.0. This runs even on bionic. B.Oops 1.2.8 with this and other compatibility fixes will follow soon.

Another option may be updating lv2. But take care not to break other dependencies.

**Comment by eufex** [comment]
Cheers :) I'll give it a go.

**Comment by eufex** [comment]
Yup - built and working in Ardour :) Thx
