### ISSUE TITLE
strange behavior when triggering patterns

### ISSUE THREAD

**Issue by ghost** [sjaehn/BOops#17]
hi, i'm trying to trigger effects using midi, and i'm doing this by making patterns with only one effect and triggering those, but i seem to have run into a bug. whenever i trigger one effect, it works as expected, but when i trigger the next, the first effect seems to play along with the second one? whenever i play on my keyboard, the first effect seems to go away after it gets triggered once, but it always happens along with the second effect whenever i sequence it

feel free to ask for elaboration, i'm not good at explaining things

**Comment by sjaehn** [comment]
I just responded on https://linuxmusicians.com/viewtopic.php?f=48&t=23327 .

Anyway, I know it's a bit quirky and I've to think about how to make it more intuitive AND to keep compatibility.

**Comment by sjaehn** [comment]
What about this:

![Bildschirmfoto von 2021-06-07 18-30-54](https://user-images.githubusercontent.com/42939779/121056585-a1f78900-c7be-11eb-8b95-f9c53da6fa05.png)

**Comment by ghost** [comment]
> What about this:
> 
> ![Bildschirmfoto von 2021-06-07 18-30-54](https://user-images.githubusercontent.com/42939779/121056585-a1f78900-c7be-11eb-8b95-f9c53da6fa05.png)

how did you get that?

**Comment by sjaehn** [comment]
Only an idea. Not pushed yet to this repository.

**Comment by ghost** [comment]
that would work!
