### ISSUE TITLE
Global "bypass" parameter

### ISSUE THREAD

**Issue by mikelupe** [sjaehn/BOops#18]
First of all thanks for the lovely plugin and the integration of AW effects.

It would be very helpful to be able to automate a global bypass parameter in the DAWs, e.g. Ardour. Thanks.

**Comment by sjaehn** [comment]
It's already in there :-). The green / yellow / red buttons for play / **bypass** / stop can be automated via the "Play" parameter (atm port 6) with 0 = stop, 1 = play, 2 = bypass.

**Comment by mikelupe** [comment]
Great, I saw that! 

The only thing is, as far as I've seen, this stops the sequencer on a beat and continues on the same one when re-enabled. Is there a way to reset it to the beginning of the sequence? Or do I miss something? It wouldn't be the first time this happens to me ;)

edit: I'll play around with the "bypass" button, I have to find out, how to not disable the track's audio, when using it (that's what happens now)

**Comment by sjaehn** [comment]
> ... as far as I've seen, this stops the sequencer on a beat and continues on the same one when re-enabled.

Nope. The plugin receives the position data from the host (DAW) in the host controlled mode and in the MIDI controlled mode. If there are no position data submitted by the DAW or you are in the autoplay mode, then the plugin **continues** with progression in the normal way (even if output bypassed or stopped).

> Is there a way to reset it to the beginning of the sequence?

This wouldn't make sense following the description above. The host dictates the position. BUT, there is a way. the "MIDI triggered" mode. This mode allows to "Restart" if a certain note is pressed.

> I'll play around with the "bypass" button, I have to find out, how to not disable the track's audio, when using it (that's what happens now)

0 mutes the output, 2 bypasses. Works fine. At least with me.

**Comment by mikelupe** [comment]
Ok, thanks for the explanations. The "muted" audio source when bypassing might be some other issue with my routing.

I'll post it here, as soon as I find the reason. Ignore this issue for the time being :)

**Comment by mikelupe** [comment]
I did some tests and it could seem to be a specific situation. Maybe you find some time to reproduce this:
Debian 11, KDE, Jack2, Ardour 6.7 with a Helm softsynth track 8 bars and some notes, BOops on it with e.g. "Bobble wobble" preset.
It starts playing with the effect audible, and when pressing yellow bypass, the filter correctly goes away and only the source audio plays. But when clicking again the yellow bypass, the source audio is gone and there's only silence. I have to press again the green play button for everything to come back. If this is expected,  will close this issue. 

Again: lovely plugin!

**Comment by sjaehn** [comment]
This is right. Both, play button and bypass button are toggle buttons. If you press them for a second time, they become unselected. And if nothing is selected, then playback stops (= muted).
