### ISSUE TITLE
directly trigger effects via midi

### ISSUE THREAD

**Issue by ghost** [sjaehn/BOops#19]
note: if there's already a way to do this, please tell me!

anyways, it would be nice if you could directly trigger individual effects via midi without having to use patterns. i find that using the patterns is a bit finicky, and i'd love to be able to create complex effect sequences in my daw without having to program every bar or whatever individually (and there are only sixteen of them anyway, so)

**Comment by sjaehn** [comment]
Thanks for your FR. I had this option in my mind from the beginning, but I decided to enable to other ways first (_vide infra_). But we will see if there won't be this third way in the future.

I the present version, you can:

- Trigger re-start of pattern playback by at least one pre-selected MIDI note. Pressing a piano key then results in a pattern jump back.
- Switch between multiple patterns by a pre-selected MIDI signal (NOTE_ON, NOTE_OFF, CC, ...).

The second case is similar to the MIDI-triggered preset change of some VST effect sequencers. And it _partially_ enables the flexibility you wanted. I think you already found out this way (reading your comment).

But direct effect triggering is sth. to keep in mind for future versions.

**Comment by sjaehn** [comment]
Just an idea (GIMP draft):
![boops_piano](https://user-images.githubusercontent.com/42939779/128631144-391644e2-9c9e-487d-9dc8-a785e266f5ad.png)

Add a third slot mode: piano roll. You will be able to switch between pattern, shape or piano-triggered mode by clicking the button left to the pattern/shape/piano roll. Select the keys to respond by clicking on the piano roll. What do you think about?

**Comment by ghost** [comment]
that looks great!

**Comment by sjaehn** [comment]
Requested feature now implemented by the latest series of commits. Have fun with it. I already had :-).
