### ISSUE TITLE
Randomise patterns via midi

### ISSUE THREAD

**Issue by hellocatfood** [sjaehn/BOops#20]
I have a several effects and patterns setup for a live performance and I'd like to be able to randomise it using a midi controller. 

I looked through the plugin's parameters in Carla and it looks like this option isn't exposed to be controlled via midi and it seems this can only be done via the gui using the dice button.

Can this option be added?

**Comment by sjaehn** [comment]
You have to define first how to respond to MIDI signals. As you have got up to 16 patterns (tabs). Click the piano symbol on the tab and define a MIDI signal to respond to (or simply use MIDI learn, but take care about the velocity (value) parameter).
![Clip](https://user-images.githubusercontent.com/42939779/131305291-4782b274-d839-43d6-b659-f425c45c3581.png)

These setup parameters are indeed not exposed. This would be 64 ( = 16 * 4) additional parameters with only limited benefit.

The dice button is only for the randomization of the present shown pattern.

**Comment by sjaehn** [comment]
Added to README.md in 914a244c5867df3383ef494c47e998b1e0ad9f47
