### ISSUE TITLE
Keyboard notes selected for effects do not persist

### ISSUE THREAD

**Issue by jeffbeale** [sjaehn/BOops#22]
Steps to reproduce:
Select notes for each effect (I used C1-F1)
Put your computer to sleep, close the session, or do something that causes the RAM to flush
B.Oops had an oopsie and now is defaulted to curve selection rather than note selection for the effects.

**Comment by sjaehn** [comment]
Thanks for report. Which version of B.Oops do you use? And which host (DAW)? State save & restore of the slot keys was not supported in the developers versions before 1.7.14. But it should work in 1.8.0 (just tested). If you observe not persisting notes in in 1.8.0, then it's an odd bug and I need more information.

**Comment by jeffbeale** [comment]
Sorry, had to type this out in a hurry before bed. B.Oops 1.8.0 installed using the instructions in the readme, inside Ardour 6.9.0. Is this an Ardour bug?

**Comment by sjaehn** [comment]
<strike>Strange, this is exactly one of my testing scenarios. Are you able to provide a step by step information what you did. Or a video?</strike>

Now I can reproduce it. I'll analyze and fix it.

**Comment by sjaehn** [comment]
Bug fixed in adc6af5c48ee9fc064f6f3bb88959af0ae30be67 .  Thanks for reporting.

**Comment by jeffbeale** [comment]
Awesome! Excited for the next update - this bug was making it hard to work on a remix I was doing.
