### ISSUE TITLE
BOops and Ardour crashes when I remove one of the effects.

### ISSUE THREAD

**Issue by tonilink** [sjaehn/BOops#24]
Using Ardour 6.9 official build. BOops 1.8.2.
It does not matter if is playing or paused. 
How to reproduce: 
Create a new Ardour session. Add a Audio track. Put Boops in this track. Ad a reverb, remove, and crash.

**Comment by sjaehn** [comment]
Thanks for reporting. But I can't reproduce it with Ardour 6.9.0 and B.Oops master. Do you get some (command line) output on crashing? Maybe this can help. Can someone else reproduce this bug?

**Comment by tonilink** [comment]
Runing using command line don't show logs from the crash:

antonio@xlr:~ /opt/Ardour-6.9.0/bin/ardour6
Ardour6.9.0 (built using 6.9 and GCC version 6.3.0 20170516)
Ardour: [INFO]: Your system is configured to limit Ardour to 1048576 open files
Ardour: [INFO]: Loading system configuration file /opt/Ardour-6.9.0/etc/system_config
Ardour: [INFO]: Loading user configuration file /home/antonio/.config/ardour6/config
Ardour: [INFO]: CPU vendor: GenuineIntel
Ardour: [INFO]: AVX-capable processor
Ardour: [INFO]: AVX with FMA capable processor
Ardour: [INFO]: CPU brand: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Ardour: [INFO]: Using AVX and FMA optimized routines
Ardour: [INFO]: Loading plugin meta data file /opt/Ardour-6.9.0/share/plugin_metadata/plugin_tags
Ardour: [INFO]: Loading plugin statistics file /home/antonio/.config/ardour6/plugin_metadata/plugin_stats
Cannot xinstall SIGPIPE error handler
Ardour: [INFO]: Loading default ui configuration file /opt/Ardour-6.9.0/etc/default_ui_config
Ardour: [INFO]: Loading user ui configuration file /home/antonio/.config/ardour6/ui_config
Gtk-Message: Failed to load module "canberra-gtk-module"
Ardour: [INFO]: Loading color file /opt/Ardour-6.9.0/share/themes/dark-ardour.colors
Ardour: [INFO]: Loading color file /home/antonio/.config/ardour6/my-dark-ardour.colors
Ardour: [INFO]: Loading ui configuration file /opt/Ardour-6.9.0/etc/clearlooks.rc
Ardour: [INFO]: Loading 452 MIDI patches from /opt/Ardour-6.9.0/share/patchfiles
Ardour: [INFO]: Loading bindings from /home/antonio/.config/ardour6/ardour.keys
Loading ui configuration file /opt/Ardour-6.9.0/etc/clearlooks.rc
ALSA: Cannot open device 'hw:PCH,0': Device or resource busy
ALSA: Cannot open device 'hw:PCH,0': Device or resource busy
ALSA: Cannot open device 'hw:PCH,0': Device or resource busy
ALSA: Cannot open device 'hw:PCH,0': Device or resource busy
ALSA: Cannot open device 'hw:PCH,0': Device or resource busy
ALSA: Cannot open device 'hw:PCH,0': Device or resource busy
ALSA: Cannot open device 'hw:PCH,0': Device or resource busy
ALSA: Cannot open device 'hw:PCH,0': Device or resource busy
ALSA: Cannot open device 'hw:PCH,0': Device or resource busy
ALSA: Cannot open device 'hw:PCH,0': Device or resource busy
error: failed to open file /home/antonio/.lv2/geonkick.lv2(debianSid).zip/manifest.ttl (Not a directory)
lilv_world_load_file(): error: Error loading file `file:///home/antonio/.lv2/geonkick.lv2(debianSid).zip/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/antonio/.lv2/geonkick.lv2(debianSid).zip/manifest.ttl
lilv_world_add_plugin(): warning: Duplicate plugin <http://tytel.org/helm>
lilv_world_add_plugin(): warning: ... found in file:///home/antonio/.lv2/helm.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/helm.lv2/ (ignored)
Scanning folders for bundled LV2s: /opt/Ardour-6.9.0/lib/LV2
error: failed to open file /home/antonio/.lv2/geonkick.lv2(debianSid).zip/manifest.ttl (Not a directory)
lilv_world_load_file(): error: Error loading file `file:///home/antonio/.lv2/geonkick.lv2(debianSid).zip/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/antonio/.lv2/geonkick.lv2(debianSid).zip/manifest.ttl
lilv_world_add_plugin(): warning: Duplicate plugin <http://tytel.org/helm>
lilv_world_add_plugin(): warning: ... found in file:///home/antonio/.lv2/helm.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/helm.lv2/ (ignored)
Set cursor set to default
Killed
antonio@xlr:~$ watched PID no longer exists - releasing device.

**Comment by tonilink** [comment]
Screencast:

https://youtu.be/dLFWnliiNUc

I'm working around it just never removing the effects from the plugin, just changing those that I no longer use. Ignoring this, the plugin is perfect.

**Comment by sjaehn** [comment]
I watched your video and I tried to reproduced it. I even run ardour in the alsa mode and used the big buffer size of 4096 you used too. But I still can't reproduce the crash. Maybe it's something related to alsa messages:
```
ALSA: Cannot open device 'hw:PCH,0': Device or resource busy
```

But it really look unrelated to the alsa problem that the crash happens after removing an effect slot. Nevertheless I now know where I have to look into the B.Oops code as I suspect illegal memory access following the remove of an effect.

**Comment by tonilink** [comment]
Testing with Jack (Pipewire) and no Alsa errors:

antonio@xlr:~$ /opt/Ardour-6.9.0/bin/ardour6
Ardour6.9.0 (built using 6.9 and GCC version 6.3.0 20170516)
Ardour: [INFO]: Your system is configured to limit Ardour to 1048576 open files
Ardour: [INFO]: Loading system configuration file /opt/Ardour-6.9.0/etc/system_config
Ardour: [INFO]: Loading user configuration file /home/antonio/.config/ardour6/config
Ardour: [INFO]: CPU vendor: GenuineIntel
Ardour: [INFO]: AVX-capable processor
Ardour: [INFO]: AVX with FMA capable processor
Ardour: [INFO]: CPU brand: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Ardour: [INFO]: Using AVX and FMA optimized routines
Ardour: [INFO]: Loading plugin meta data file /opt/Ardour-6.9.0/share/plugin_metadata/plugin_tags
Ardour: [INFO]: Loading plugin statistics file /home/antonio/.config/ardour6/plugin_metadata/plugin_stats
Cannot xinstall SIGPIPE error handler
Ardour: [INFO]: Loading default ui configuration file /opt/Ardour-6.9.0/etc/default_ui_config
Ardour: [INFO]: Loading user ui configuration file /home/antonio/.config/ardour6/ui_config
Gtk-Message: Failed to load module "canberra-gtk-module"
Ardour: [INFO]: Loading 452 MIDI patches from /opt/Ardour-6.9.0/share/patchfiles
Ardour: [INFO]: Loading color file /opt/Ardour-6.9.0/share/themes/dark-ardour.colors
Ardour: [INFO]: Loading color file /home/antonio/.config/ardour6/my-dark-ardour.colors
Ardour: [INFO]: Loading ui configuration file /opt/Ardour-6.9.0/etc/clearlooks.rc
Ardour: [INFO]: Loading bindings from /home/antonio/.config/ardour6/ardour.keys
Loading ui configuration file /opt/Ardour-6.9.0/etc/clearlooks.rc
Scanning folders for bundled LV2s: /opt/Ardour-6.9.0/lib/LV2
Set cursor set to default
Killed

Screencast:
https://youtu.be/GknVcpSujk0

I've tested it in Kubuntu 21.10, Debian Stable, Debian Sid and Fedora 35 with both, Pipewire, real Jack (without Pipewire), Alsa and Pulseaudio as backends, it always crash in the same way.

**Comment by sjaehn** [comment]
Thanks for demonstration. I did some checks but I still can't find the point of crash. I suspect some illegal memory access but the memcheck tool `valgrind` doesn't tell anything suspicious (at least if tested with `jalv`. So I still can't reproduce it and still groping in the dark.

Maybe you (or anybody else who also experienced this bug) can help:
* Do you use a self-compiled version or do you use binaries provided by your distro?
* Does this problem also occur within other plugin hosts on your system? Like `carla` or `jalv`. Or even `Reaper` or whatever?
* If the problem can be reproduced in `jalv` and you have some experience with debugging (`gdb`), then try to compile and debug:
  ```
  make CPPFLAGS+=-g     # Compile with debug symbols
  sudo make install PREFIX=/usr     # Install to PREFIX/lib/lv2/BOops.lv2 (or change the PREFIX)
  gdb jalv.gtk3    # Or any other jalv you like to use
  ```
  Inside gdb, call
  ```
  run https://www.jahnichen.de/plugins/lv2/BChoppr
  ```
  Then it should produce an informative backtrace (`bt`) following the crash.

**Comment by tonilink** [comment]
I'm using a self-compiled version.
I've tested B.Oops inside Carla (opening via terminal) and nothing happens, and no message logs appears.
And testing via jalv, no crashes too.

It's seems that's Ardour again. 🥲

**Comment by sjaehn** [comment]
Thanks. And of course it could be the case that Ardour is the "bad boy" which tries some illegal memory access. And if this memory is already occupied by B.Oops. Then *bang!*
