### ISSUE TITLE
Add bypass option

### ISSUE THREAD

**Issue by hellocatfood** [sjaehn/BOops#25]
Can a bypass option be added to this plugin?

The rationale behind this is request: 

I use B.Oops in live performances. I have a glitch effects stack/preset already set up and I want to enable it whenever I press a button on a midi controller. Currently this isn't possible as there's no bypass option

**Comment by sjaehn** [comment]
B.Oops has already got implemented many ways to bypass.

- You can bypass all effects at once using the yellow bypass button just below the word "EFFECT". The three play/bypass/stop buttons are connected to the lv2 control port 6 ("Play" port). 
- You can bypass each single effect by switching off the play symbol right to the respective effect. Each of these play buttons are connected to lv2 control ports called "Slot xx play".
- And of course you can bypass each effect by setting the effects dry/wet mix parameter to full dry (0.0). And no surprise, also these dials are connected to lv2 ports ("Slot xx dry / wet").

Now, you only need to connect your midi controller to lv2 control ports. The way how it works depends on the system or DAW or program whatever you use.

... and there is one more "inverse" option. The "MIDI" mode. Click onto the pattern/curve/piano symbol left to the pattern matrix until the piano pattern appears. Select keys and the respective effect is bypassed if the key (or MIDI controller) isn't pressed.

**Comment by hellocatfood** [comment]
> You can bypass all effects at once using the yellow bypass button just below the word "EFFECT". The three play/bypass/stop buttons are connected to the lv2 control port 6 ("Play" port).

Not sure how I missed this! I mainly use Ardour as my plugin host (even for live performances) and in the Automation settings it just shows "Play" and so I just assumed it only affected whether it was playing or not.

![Screenshot from 2022-08-24 22-44-48](https://user-images.githubusercontent.com/151947/186529307-efccaa7a-70e7-480c-8315-f1b6b7924e50.png)

Thanks for all of the extra information!
